clear;
N = 256;
binary_size = 9;
data = (0:N)';
b_data = flip(de2bi(data, binary_size),2);
dir = "./";
add_path = "add_emb.mat";
load(dir+add_path);
emb = double(emb);
data_emb_add = b_data*emb;
[coeff_add, score_add] = pca(data_emb_add);
c = cellstr(num2str(data));
c{end} = 'Inf';
dx = 0;
dy = 0;
dz = 0;
pos = -(2*mod(data,2)-1);
font_size = 15;
msize = 100;
figure;
scatter3(score_add(:,1), score_add(:,2), score_add(:,3), msize, data, 'filled');
text(score_add(:,1), score_add(:,2), score_add(:,3), c, 'Fontsize', font_size);
xlim([min(score_add(:,1))-dx, max(score_add(:,1))+dx]);
ylim([min(score_add(:,2))-dy, max(score_add(:,2))+dy]);
zlim([min(score_add(:,3))-dz, max(score_add(:,3))+dz]);