clear;
N = 255;
binary_size = 12;
data = (0:N)';
b_data = flip(de2bi(data, binary_size),2);
dir = "./";
mul_path = "mul_emb.mat";
load(dir+mul_path);
emb = double(emb);
data_emb_mul = b_data*emb;
[coeff_mul, score_mul] = pca(data_emb_mul);
c = cellstr(num2str(data));
c{end} = 'Inf';
dx = 0;
dy = 0;
dz = 0;
pos = -(2*mod(data,2)-1);
font_size = 15;
msize = 100;
figure;
scatter3(score_mul(:,1), score_mul(:,2), score_mul(:,3), msize, data, 'filled');
text(score_mul(:,1), score_mul(:,2), score_mul(:,3), c, 'Fontsize', font_size);
xlim([min(score_mul(:,1))-dx, max(score_mul(:,1))+dx]);
ylim([min(score_mul(:,2))-dy, max(score_mul(:,2))+dy]);
zlim([min(score_mul(:,3))-dz, max(score_mul(:,3))+dz]);