clear;
N = 256;
binary_size = 10;
data = (0:N)';
b_data = flip(de2bi(data, binary_size),2);
dir = "./";
sort_path = "sel_sort_emb.mat";
load(dir+sort_path);
emb = double(emb);
data_emb_sort = b_data*emb;
[coeff_sort, score_sort] = pca(data_emb_sort);
c = cellstr(num2str(data));
c{end} = 'Inf';
dx = 0;
dy = 0;
dz = 0;
pos = -(2*mod(data,2)-1);
font_size = 15;
msize = 100;
figure;
scatter3(score_sort(:,1), score_sort(:,2), score_sort(:,3), msize, data, 'filled');
text(score_sort(:,1), score_sort(:,2), score_sort(:,3), c, 'Fontsize', font_size);
xlim([min(score_sort(:,1))-dx, max(score_sort(:,1))+dx]);
ylim([min(score_sort(:,2))-dy, max(score_sort(:,2))+dy]);
zlim([min(score_sort(:,3))-dz, max(score_sort(:,3))+dz]);